Algoritmo "Ex 01"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Gustavo Guanabara
// Descrição   : Escreva um programa que mostre na tela a mensagem "Olá, Mundo!"
// Autor(a)    : Wanderson Ribeiro
// Data atual  : 27/05/2022

Var
// Seção de Declarações das variáveis 


Inicio
      Escreval ("Olá, mundo!")
      Escreval ("Hello, World!")
      Escreval (" ")
      Escreva ("Me livrei da maldição =D ")


Fimalgoritmo